---
abstract: 'Throttle just about anything with ease'
author:
  - 'David Morel <david.morel@amakuru.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schedule-AdaptiveThrottler
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 0
  Test::More: 0
version: 0.06
